### ISSUE TITLE
Packaging gtk3-classic for Ubuntu

### ISSUE THREAD

**Issue by lah7** [lah7/gtk3-mushrooms#43]
Ubuntu MATE users in particular may enjoy the patches from this project. However, creating Debian packaging for GTK+3 has been more cumbersome then expected. 

I've had 2 attempts this year, but been unable to get a complete build, so leaving progress here if any one wishes to have a go.

### :x: First Attempt

By working on a "fork" of the original `gtk+3.0` source packaging, and submit to Launchpad to build. 
  * Can't build locally with normal means (`debuild -b`), `debian/README.source` mentions this, but it does successfully build on Launchpad. 
  * Was thinking of [a script](https://github.com/lah7/gtk3-classic/blob/ubuntu-packaging/scripts/create-ubuntu-package.sh) to automate the process, and add/replace our patches (there are some already, and one conflicts with ours).
  * It would use the same package structure/names as the real `gtk3`, but could suffix the version like `3.24.20~classic`?
  * This method might work if we append our patches/series into the Ubuntu packaging.
  * **Abandoned idea for now** because it makes things more difficult for users to revert their packages back to the original.

### 🔥 Second Attempt

[Create a single `gtk3-classic` package](https://github.com/lah7/gtk3-classic/blob/ubuntu-packaging/debian/control) to replace/provide the original gtk3 dependencies, which is similar to how `gtk3` and `gtk3-classic` are packaged for Arch.
  * Uses meson/ninja as a build system.
  * This should be easier to maintain.
  * The problem is that it fails to build (under Ubuntu 21.10) due to compilation errors, even before we apply our patches.

### Reproducing so far
Running on Ubuntu 21.10 (GTK 3.24.30) - most current version.

```bash
sudo apt-get build-dep gtk+3.0
sudo apt-get install meson ninja-build

git clone https://github.com/lah7/gtk3-classic -b ubuntu-packaging
cd gtk3-classic
apt source gtk+3.0
rm -rf gtk+3.0-3.24.30
tar -xJf gtk+3.0_3.24.30.orig.tar.xz
meson gtk+-3.24.30 build \
		-D broadway_backend=true \
		-D colord=no \
		-D demos=true \
		-D examples=true \
		-D tests=false \
		-D installed_tests=false \
		-D gtk_doc=false
DESTDIR=dist ninja -C build install
```

Unless the compilation errors are too serious, maybe there's a way to prevent warnings becoming errors? Maybe we need Debian's/Ubuntu's patches for it to build on Ubuntu?

[Here's Arch's build() step for reference](https://github.com/lah7/gtk3-classic/blob/master/PKGBUILD#L111-L123)

#### Logs

* Meson/Ninja locally: [error.log](https://github.com/lah7/gtk3-classic/files/7796507/build-error.log)
* Launchpad: [buildlog_ubuntu-impish-amd64.gtk3-classic_3.24.20-1_BUILDING.txt.gz](https://github.com/lah7/gtk3-classic/files/7796508/buildlog_ubuntu-impish-amd64.gtk3-classic_3.24.20-1_BUILDING.txt.gz)

----

I have a gist bookmarked from @N0rbert, whom created a script based on one I created for 18.04, 19.04 and 19.10, which could be useful.

https://gist.github.com/N0rbert/2141ad87fcb91f67cad438293ec46986

**Comment by lah7** [comment]
Ubuntu now has packages! [Feel free to give them a try.](https://github.com/lah7/gtk3-classic#ubuntu)
